apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-volume
spec:
  volumeMode: Filesystem
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - hard
    - noatime
  nfs:
    path: /volume1/k8s
    server: nas.local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: registry
  labels:
    app: registry
spec:
  containers:
    - name: registry
      image: registry:2
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /var/lib/registry
          name: registry-data
  restartPolicy: Always
  volumes:
    - name: registry-data
      persistentVolumeClaim:
        claimName: registry-volume
---
apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  selector:
    app: registry
  ports:
    - port: 5000
  type: LoadBalancer
