---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Install nginx
      shell: |
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
        helm repo update
        helm install nginx-ingress ingress-nginx/ingress-nginx

    - name: Install sacred
      shell:
        kubec
