---
- hosts: all
  tasks:
    - name: Install curl
      apt:
        name: curl

    - name: Install nfs (for nfs provider)
      apt:
        name: nfs-common

    - name: Uninstall k3s
      command: k3s-uninstall.sh
      ignore_errors: yes

    - name: Download install script
      get_url:
        url: https://get.k3s.io
        dest: /root/install.sh
        mode: 0700

    - name: Move files to remote host
        copy:
          force: yes
          src: hosts
          dest: "/etc/hosts"

- hosts: master
  tasks:
    - name: Initialize server
      command: /root/install.sh --no-deploy traefik --no-deploy servicelb --no-deploy local-storage
      environment:
        K3S_DATASTORE_ENDPOINT: postgres://postgres:postgres@nas.hnatekmar.xyz:32773/postgres?sslmode=disable
        INSTALL_K3S_VERSION: v1.19.7+k3s1
    - name: Get node-token
      command: cat /var/lib/rancher/k3s/server/node-token
      register: node_token

    - name: Register node_token as global var
      connection: local
      copy:
        dest: .node_token
        content: "{{ node_token.stdout }}"

    - name: Register master ip as global var
      connection: local
      copy:
        dest: .master_ip
        content: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

    - name: Download kubeconfig
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ~/.kube/config
        flat: yes

    - name: Replace
      connection: local
      replace:
        path: ~/.kube/config
        regexp: "127.0.0.1"
        replace: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

- hosts: workers
  tasks:
    - name: Move files to remote host
      copy:
        force: yes
        src: "{{ item }}"
        dest: "/root/{{ item }}"
      loop:
        - .master_ip
        - .node_token
    - name: Copy install script for worker
      copy:
        force: yes
        dest: ./install_worker.sh
        content: |
          #!/bin/bash
          export K3S_URL="https://$(cat /root/.master_ip):6443"
          export K3S_TOKEN=$(cat ~/.node_token)
          /root/install.sh
    - name: Initialize server
      command: bash /root/install_worker.sh
      environment:
        INSTALL_K3S_VERSION: v1.19.7+k3s1
